<?php

namespace Database\Seeders;

use App\Models\RecipeIngredientUnit;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class RecipeIngredientUnitTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        RecipeIngredientUnit::truncate();

        $recipeingredientunits = [
            [
                'recipe_id' => 1,
                'ingredient_id' => 139,
                'unit_id' => 3,
                'value' => 2.5,
            ],
            [
                'recipe_id' => 1,
                'ingredient_id' => 166,
                'unit_id' => 3,
                'value' => 2.5,
            ],
            [
                'recipe_id' => 1,
                'ingredient_id' => 13,
                'unit_id' => 3,
                'value' => 5,
            ],
            [
                'recipe_id' => 1,
                'ingredient_id' => 67,
                'unit_id' => 3,
                'value' => 355,
            ],
            [
                'recipe_id' => 1,
                'ingredient_id' => 14,
                'unit_id' => null,
                'value' => 4,
            ],
            [
                'recipe_id' => 1,
                'ingredient_id' => 62,
                'unit_id' => null,
                'value' => 2,
            ],
            [
                'recipe_id' => 1,
                'ingredient_id' => 152,
                'unit_id' => 3,
                'value' => 240,
            ],
            [
                'recipe_id' => 1,
                'ingredient_id' => 30,
                'unit_id' => 3,
                'value' => 120,
            ],
            [
                'recipe_id' => 2,
                'ingredient_id' => 140,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 2,
                'ingredient_id' => 30,
                'unit_id' => 1,
                'value' => 100,
            ],
            [
                'recipe_id' => 2,
                'ingredient_id' => 134,
                'unit_id' => 2,
                'value' => 300,
            ],
            [
                'recipe_id' => 2,
                'ingredient_id' => 25,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 2,
                'ingredient_id' => 34,
                'unit_id' => 3,
                'value' => 120,
            ],
            [
                'recipe_id' => 2,
                'ingredient_id' => 30,
                'unit_id' => null,
                'value' => 4,
            ],
            [
                'recipe_id' => 2,
                'ingredient_id' => 27,
                'unit_id' => 1,
                'value' => 600,
            ],
            [
                'recipe_id' => 3,
                'ingredient_id' => 102,
                'unit_id' => 1,
                'value' => 80,
            ],
            [
                'recipe_id' => 3,
                'ingredient_id' => 19,
                'unit_id' => null,
                'value' => 2,
            ],
            [
                'recipe_id' => 3,
                'ingredient_id' => 53,
                'unit_id' => 10,
                'value' => 2,
            ],
            [
                'recipe_id' => 3,
                'ingredient_id' => 139,
                'unit_id' => 7,
                'value' => 3,
            ],
            [
                'recipe_id' => 3,
                'ingredient_id' => 163,
                'unit_id' => 1,
                'value' => 500,
            ],
            [
                'recipe_id' => 3,
                'ingredient_id' => 162,
                'unit_id' => 5,
                'value' => 2,
            ],
            [
                'recipe_id' => 3,
                'ingredient_id' => 134,
                'unit_id' => 6,
                'value' => 0.5,
            ],
            [
                'recipe_id' => 3,
                'ingredient_id' => 80,
                'unit_id' => 1,
                'value' => 300,
            ],
            [
                'recipe_id' => 3,
                'ingredient_id' => 79,
                'unit_id' => 1,
                'value' => 300,
            ],
            [
                'recipe_id' => 3,
                'ingredient_id' => 115,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 3,
                'ingredient_id' => 37,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 3,
                'ingredient_id' => 34,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 3,
                'ingredient_id' => 114,
                'unit_id' => 5,
                'value' => 2,
            ],
            [
                'recipe_id' => 4,
                'ingredient_id' => 177,
                'unit_id' => 5,
                'value' => 0.5,
            ],
            [
                'recipe_id' => 4,
                'ingredient_id' => 29,
                'unit_id' => 5,
                'value' => 1,
            ],
            [
                'recipe_id' => 4,
                'ingredient_id' => 104,
                'unit_id' => 5,
                'value' => 1.5,
            ],
            [
                'recipe_id' => 4,
                'ingredient_id' => 15,
                'unit_id' => 6,
                'value' => 1,
            ],
            [
                'recipe_id' => 4,
                'ingredient_id' => 114,
                'unit_id' => 5,
                'value' => 2,
            ],
            [
                'recipe_id' => 4,
                'ingredient_id' => 35,
                'unit_id' => 4,
                'value' => 0.75,
            ],
            [
                'recipe_id' => 4,
                'ingredient_id' => 57,
                'unit_id' => 4,
                'value' => 0.5,
            ],
            [
                'recipe_id' => 4,
                'ingredient_id' => 53,
                'unit_id' => 4,
                'value' => 0.5,
            ],
            [
                'recipe_id' => 4,
                'ingredient_id' => 139,
                'unit_id' => 4,
                'value' => 1.5,
            ],
            [
                'recipe_id' => 4,
                'ingredient_id' => 120,
                'unit_id' => 4,
                'value' => 1,
            ],
            [
                'recipe_id' => 4,
                'ingredient_id' => 116,
                'unit_id' => 4,
                'value' => 0.5,
            ],
            [
                'recipe_id' => 4,
                'ingredient_id' => 71,
                'unit_id' => 4,
                'value' => 1,
            ],
            [
                'recipe_id' => 4,
                'ingredient_id' => 20,
                'unit_id' => 1,
                'value' => 1000,
            ],
            [
                'recipe_id' => 5,
                'ingredient_id' => 114,
                'unit_id' => 5,
                'value' => 1,
            ],
            [
                'recipe_id' => 5,
                'ingredient_id' => 6,
                'unit_id' => 14,
                'value' => 1,
            ],
            [
                'recipe_id' => 5,
                'ingredient_id' => 102,
                'unit_id' => 2,
                'value' => 10,
            ],
            [
                'recipe_id' => 5,
                'ingredient_id' => 62,
                'unit_id' => null,
                'value' => 4,
            ],
            [
                'recipe_id' => 5,
                'ingredient_id' => 38,
                'unit_id' => 1,
                'value' => 75,
            ],
            [
                'recipe_id' => 5,
                'ingredient_id' => 113,
                'unit_id' => 1,
                'value' => 150,
            ],
            [
                'recipe_id' => 5,
                'ingredient_id' => 81,
                'unit_id' => 1,
                'value' => 200,
            ],
            [
                'recipe_id' => 5,
                'ingredient_id' => 67,
                'unit_id' => 1,
                'value' => 150,
            ],
            [
                'recipe_id' => 6,
                'ingredient_id' => 139,
                'unit_id' => 7,
                'value' => 1,
            ],
            [
                'recipe_id' => 6,
                'ingredient_id' => 30,
                'unit_id' => 1,
                'value' => 50,
            ],
            [
                'recipe_id' => 6,
                'ingredient_id' => 152,
                'unit_id' => 1,
                'value' => 250,
            ],
            [
                'recipe_id' => 6,
                'ingredient_id' => 67,
                'unit_id' => 1,
                'value' => 100,
            ],
            [
                'recipe_id' => 6,
                'ingredient_id' => 174,
                'unit_id' => 5,
                'value' => 1,
            ],
            [
                'recipe_id' => 6,
                'ingredient_id' => 167,
                'unit_id' => null,
                'value' => 0.5,
            ],
            [
                'recipe_id' => 6,
                'ingredient_id' => 63,
                'unit_id' => null,
                'value' => 2,
            ],
            [
                'recipe_id' => 6,
                'ingredient_id' => 62,
                'unit_id' => null,
                'value' => 2,
            ],
            [
                'recipe_id' => 6,
                'ingredient_id' => 102,
                'unit_id' => 2,
                'value' => 50,
            ],
            [
                'recipe_id' => 7,
                'ingredient_id' => 109,
                'unit_id' => 5,
                'value' => 3,
            ],
            [
                'recipe_id' => 7,
                'ingredient_id' => 87,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 7,
                'ingredient_id' => 30,
                'unit_id' => 1,
                'value' => 30,
            ],
            [
                'recipe_id' => 7,
                'ingredient_id' => 75,
                'unit_id' => 8,
                'value' => 5,
            ],
            [
                'recipe_id' => 7,
                'ingredient_id' => 11,
                'unit_id' => 1,
                'value' => 250,
            ],
            [
                'recipe_id' => 7,
                'ingredient_id' => 115,
                'unit_id' => 1,
                'value' => 400,
            ],
            [
                'recipe_id' => 7,
                'ingredient_id' => 3,
                'unit_id' => 3,
                'value' => 1000,
            ],
            [
                'recipe_id' => 7,
                'ingredient_id' => 25,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 7,
                'ingredient_id' => 29,
                'unit_id' => 5,
                'value' => 1,
            ],
            [
                'recipe_id' => 7,
                'ingredient_id' => 89,
                'unit_id' => 1,
                'value' => 1000,
            ],
            [
                'recipe_id' => 8,
                'ingredient_id' => 5,
                'unit_id' => 1,
                'value' => 400,
            ],
            [
                'recipe_id' => 8,
                'ingredient_id' => 59,
                'unit_id' => 1,
                'value' => 120,
            ],
            [
                'recipe_id' => 8,
                'ingredient_id' => 140,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 8,
                'ingredient_id' => 114,
                'unit_id' => 5,
                'value' => 2,
            ],
            [
                'recipe_id' => 8,
                'ingredient_id' => 63,
                'unit_id' => null,
                'value' => 4,
            ],
            [
                'recipe_id' => 8,
                'ingredient_id' => 147,
                'unit_id' => 5,
                'value' => 4,
            ],
            [
                'recipe_id' => 9,
                'ingredient_id' => 139,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 9,
                'ingredient_id' => 50,
                'unit_id' => 3,
                'value' => 250,
            ],
            [
                'recipe_id' => 9,
                'ingredient_id' => 139,
                'unit_id' => 4,
                'value' => 0.25,
            ],
            [
                'recipe_id' => 9,
                'ingredient_id' => 67,
                'unit_id' => 1,
                'value' => 250,
            ],
            [
                'recipe_id' => 9,
                'ingredient_id' => 152,
                'unit_id' => 1,
                'value' => 200,
            ],
            [
                'recipe_id' => 9,
                'ingredient_id' => 68,
                'unit_id' => 1,
                'value' => 800,
            ],
            [
                'recipe_id' => 10,
                'ingredient_id' => 39,
                'unit_id' => 1,
                'value' => 500,
            ],
            [
                'recipe_id' => 10,
                'ingredient_id' => 103,
                'unit_id' => 6,
                'value' => 1,
            ],
            [
                'recipe_id' => 10,
                'ingredient_id' => 67,
                'unit_id' => 5,
                'value' => 1,
            ],
            [
                'recipe_id' => 10,
                'ingredient_id' => 140,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 10,
                'ingredient_id' => 38,
                'unit_id' => 6,
                'value' => 1,
            ],
            [
                'recipe_id' => 10,
                'ingredient_id' => 108,
                'unit_id' => 1,
                'value' => 500,
            ],
            [
                'recipe_id' => 10,
                'ingredient_id' => 115,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 10,
                'ingredient_id' => 30,
                'unit_id' => 5,
                'value' => 4,
            ],
            [
                'recipe_id' => 11,
                'ingredient_id' => 140,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 11,
                'ingredient_id' => 150,
                'unit_id' => 5,
                'value' => 4,
            ],
            [
                'recipe_id' => 11,
                'ingredient_id' => 51,
                'unit_id' => 6,
                'value' => 4,
            ],
            [
                'recipe_id' => 11,
                'ingredient_id' => 62,
                'unit_id' => null,
                'value' => 3,
            ],
            [
                'recipe_id' => 11,
                'ingredient_id' => 70,
                'unit_id' => null,
                'value' => 2,
            ],
            [
                'recipe_id' => 11,
                'ingredient_id' => 78,
                'unit_id' => null,
                'value' => 3,
            ],
            [
                'recipe_id' => 11,
                'ingredient_id' => 34,
                'unit_id' => 6,
                'value' => 0.75,
            ],
            [
                'recipe_id' => 11,
                'ingredient_id' => 122,
                'unit_id' => 6,
                'value' => 0.75,
            ],
            [
                'recipe_id' => 11,
                'ingredient_id' => 39,
                'unit_id' => 1,
                'value' => 400,
            ],
            [
                'recipe_id' => 11,
                'ingredient_id' => 168,
                'unit_id' => 5,
                'value' => 2,
            ],
            [
                'recipe_id' => 11,
                'ingredient_id' => 141,
                'unit_id' => 5,
                'value' => 2,
            ],
            [
                'recipe_id' => 12,
                'ingredient_id' => 51,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 12,
                'ingredient_id' => 43,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 12,
                'ingredient_id' => 106,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 12,
                'ingredient_id' => 93,
                'unit_id' => null,
                'value' => 0.5,
            ],
            [
                'recipe_id' => 12,
                'ingredient_id' => 39,
                'unit_id' => 1,
                'value' => 700,
            ],
            [
                'recipe_id' => 12,
                'ingredient_id' => 50,
                'unit_id' => 6,
                'value' => 0.5,
            ],
            [
                'recipe_id' => 12,
                'ingredient_id' => 47,
                'unit_id' => 2,
                'value' => 40,
            ],
            [
                'recipe_id' => 12,
                'ingredient_id' => 162,
                'unit_id' => 5,
                'value' => 2,
            ],
            [
                'recipe_id' => 12,
                'ingredient_id' => 58,
                'unit_id' => 5,
                'value' => 1.5,
            ],
            [
                'recipe_id' => 12,
                'ingredient_id' => 105,
                'unit_id' => 4,
                'value' => 1,
            ],
            [
                'recipe_id' => 12,
                'ingredient_id' => 87,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 12,
                'ingredient_id' => 70,
                'unit_id' => null,
                'value' => 2,
            ],
            [
                'recipe_id' => 12,
                'ingredient_id' => 143,
                'unit_id' => null,
                'value' => 2,
            ],
            [
                'recipe_id' => 12,
                'ingredient_id' => 115,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 12,
                'ingredient_id' => 30,
                'unit_id' => 5,
                'value' => 1,
            ],
            [
                'recipe_id' => 12,
                'ingredient_id' => 168,
                'unit_id' => 5,
                'value' => 1,
            ],
            [
                'recipe_id' => 13,
                'ingredient_id' => 167,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 13,
                'ingredient_id' => 29,
                'unit_id' => 5,
                'value' => 6,
            ],
            [
                'recipe_id' => 13,
                'ingredient_id' => 63,
                'unit_id' => null,
                'value' => 6,
            ],
            [
                'recipe_id' => 13,
                'ingredient_id' => 152,
                'unit_id' => 1,
                'value' => 100,
            ],
            [
                'recipe_id' => 13,
                'ingredient_id' => 94,
                'unit_id' => 2,
                'value' => 50,
            ],
            [
                'recipe_id' => 14,
                'ingredient_id' => 99,
                'unit_id' => 3,
                'value' => 22,
            ],
            [
                'recipe_id' => 14,
                'ingredient_id' => 93,
                'unit_id' => 3,
                'value' => 30,
            ],
            [
                'recipe_id' => 14,
                'ingredient_id' => 174,
                'unit_id' => 3,
                'value' => 53,
            ],
            [
                'recipe_id' => 15,
                'ingredient_id' => 102,
                'unit_id' => 3,
                'value' => 1000,
            ],
            [
                'recipe_id' => 15,
                'ingredient_id' => 62,
                'unit_id' => null,
                'value' => 4,
            ],
            [
                'recipe_id' => 15,
                'ingredient_id' => 166,
                'unit_id' => 14,
                'value' => 5,
            ],
            [
                'recipe_id' => 15,
                'ingredient_id' => 152,
                'unit_id' => 1,
                'value' => 150,
            ],
            [
                'recipe_id' => 15,
                'ingredient_id' => 67,
                'unit_id' => 1,
                'value' => 250,
            ],
            [
                'recipe_id' => 16,
                'ingredient_id' => 62,
                'unit_id' => null,
                'value' => 5,
            ],
            [
                'recipe_id' => 16,
                'ingredient_id' => 67,
                'unit_id' => 5,
                'value' => 2,
            ],
            [
                'recipe_id' => 16,
                'ingredient_id' => 152,
                'unit_id' => 1,
                'value' => 250,
            ],
            [
                'recipe_id' => 16,
                'ingredient_id' => 30,
                'unit_id' => 1,
                'value' => 250,
            ],
            [
                'recipe_id' => 16,
                'ingredient_id' => 42,
                'unit_id' => 1,
                'value' => 300,
            ],
            [
                'recipe_id' => 17,
                'ingredient_id' => 114,
                'unit_id' => 4,
                'value' => 1,
            ],
            [
                'recipe_id' => 17,
                'ingredient_id' => 63,
                'unit_id' => null,
                'value' => 6,
            ],
            [
                'recipe_id' => 17,
                'ingredient_id' => 62,
                'unit_id' => null,
                'value' => 2,
            ],
            [
                'recipe_id' => 17,
                'ingredient_id' => 87,
                'unit_id' => 7,
                'value' => 1,
            ],
            [
                'recipe_id' => 17,
                'ingredient_id' => 67,
                'unit_id' => 1,
                'value' => 250,
            ],
            [
                'recipe_id' => 18,
                'ingredient_id' => 139,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 18,
                'ingredient_id' => 114,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 18,
                'ingredient_id' => 44,
                'unit_id' => null,
                'value' => 3,
            ],
            [
                'recipe_id' => 18,
                'ingredient_id' => 19,
                'unit_id' => null,
                'value' => 2,
            ],
            [
                'recipe_id' => 18,
                'ingredient_id' => 111,
                'unit_id' => 8,
                'value' => 1,
            ],
            [
                'recipe_id' => 18,
                'ingredient_id' => 53,
                'unit_id' => 4,
                'value' => 1,
            ],
            [
                'recipe_id' => 18,
                'ingredient_id' => 36,
                'unit_id' => 8,
                'value' => 1,
            ],
            [
                'recipe_id' => 18,
                'ingredient_id' => 34,
                'unit_id' => null,
                'value' => 4,
            ],
            [
                'recipe_id' => 18,
                'ingredient_id' => 143,
                'unit_id' => null,
                'value' => 4,
            ],
            [
                'recipe_id' => 18,
                'ingredient_id' => 115,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 18,
                'ingredient_id' => 101,
                'unit_id' => 2,
                'value' => 10,
            ],
            [
                'recipe_id' => 18,
                'ingredient_id' => 175,
                'unit_id' => 2,
                'value' => 20,
            ],
            [
                'recipe_id' => 18,
                'ingredient_id' => 126,
                'unit_id' => 1,
                'value' => 1200,
            ],
            [
                'recipe_id' => 19,
                'ingredient_id' => 93,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 19,
                'ingredient_id' => 55,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 19,
                'ingredient_id' => 153,
                'unit_id' => 3,
                'value' => 150,
            ],
            [
                'recipe_id' => 19,
                'ingredient_id' => 93,
                'unit_id' => 3,
                'value' => 250,
            ],
            [
                'recipe_id' => 19,
                'ingredient_id' => 164,
                'unit_id' => 3,
                'value' => 250,
            ],
            [
                'recipe_id' => 19,
                'ingredient_id' => 158,
                'unit_id' => 3,
                'value' => 500,
            ],
            [
                'recipe_id' => 20,
                'ingredient_id' => 69,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 20,
                'ingredient_id' => 63,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 20,
                'ingredient_id' => 7,
                'unit_id' => 10,
                'value' => 1,
            ],
            [
                'recipe_id' => 20,
                'ingredient_id' => 30,
                'unit_id' => 1,
                'value' => 50,
            ],
            [
                'recipe_id' => 20,
                'ingredient_id' => 62,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 20,
                'ingredient_id' => 152,
                'unit_id' => 1,
                'value' => 75,
            ],
            [
                'recipe_id' => 20,
                'ingredient_id' => 8,
                'unit_id' => 1,
                'value' => 100,
            ],
            [
                'recipe_id' => 20,
                'ingredient_id' => 130,
                'unit_id' => null,
                'value' => 2,
            ],
            [
                'recipe_id' => 21,
                'ingredient_id' => 114,
                'unit_id' => 2,
                'value' => 14,
            ],
            [
                'recipe_id' => 21,
                'ingredient_id' => 146,
                'unit_id' => 5,
                'value' => 4,
            ],
            [
                'recipe_id' => 21,
                'ingredient_id' => 124,
                'unit_id' => 1,
                'value' => 50,
            ],
            [
                'recipe_id' => 21,
                'ingredient_id' => 70,
                'unit_id' => null,
                'value' => 3,
            ],
            [
                'recipe_id' => 21,
                'ingredient_id' => 17,
                'unit_id' => 13,
                'value' => 3,
            ],
            [
                'recipe_id' => 21,
                'ingredient_id' => 87,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 22,
                'ingredient_id' => 140,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 22,
                'ingredient_id' => 94,
                'unit_id' => 1,
                'value' => 300,
            ],
            [
                'recipe_id' => 22,
                'ingredient_id' => 102,
                'unit_id' => 1,
                'value' => 300,
            ],
            [
                'recipe_id' => 22,
                'ingredient_id' => 70,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 22,
                'ingredient_id' => 128,
                'unit_id' => 1,
                'value' => 800,
            ],
            [
                'recipe_id' => 23,
                'ingredient_id' => 35,
                'unit_id' => 7,
                'value' => 1,
            ],
            [
                'recipe_id' => 23,
                'ingredient_id' => 104,
                'unit_id' => 4,
                'value' => 1,
            ],
            [
                'recipe_id' => 23,
                'ingredient_id' => 160,
                'unit_id' => null,
                'value' => 2,
            ],
            [
                'recipe_id' => 23,
                'ingredient_id' => 43,
                'unit_id' => 4,
                'value' => 3,
            ],
            [
                'recipe_id' => 23,
                'ingredient_id' => 115,
                'unit_id' => 6,
                'value' => 0.5,
            ],
            [
                'recipe_id' => 23,
                'ingredient_id' => 139,
                'unit_id' => 4,
                'value' => 1,
            ],
            [
                'recipe_id' => 23,
                'ingredient_id' => 93,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 23,
                'ingredient_id' => 10,
                'unit_id' => null,
                'value' => 3,
            ],
            [
                'recipe_id' => 24,
                'ingredient_id' => 48,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 24,
                'ingredient_id' => 42,
                'unit_id' => 14,
                'value' => 1,
            ],
            [
                'recipe_id' => 24,
                'ingredient_id' => 152,
                'unit_id' => 1,
                'value' => 100,
            ],
            [
                'recipe_id' => 24,
                'ingredient_id' => 30,
                'unit_id' => 1,
                'value' => 200,
            ],
            [
                'recipe_id' => 24,
                'ingredient_id' => 62,
                'unit_id' => null,
                'value' => 2,
            ],
            [
                'recipe_id' => 24,
                'ingredient_id' => 21,
                'unit_id' => null,
                'value' => 40,
            ],
            [
                'recipe_id' => 25,
                'ingredient_id' => 121,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 25,
                'ingredient_id' => 120,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 25,
                'ingredient_id' => 139,
                'unit_id' => 4,
                'value' => 0.5,
            ],
            [
                'recipe_id' => 25,
                'ingredient_id' => 57,
                'unit_id' => 4,
                'value' => 1,
            ],
            [
                'recipe_id' => 25,
                'ingredient_id' => 70,
                'unit_id' => null,
                'value' => 2,
            ],
            [
                'recipe_id' => 25,
                'ingredient_id' => 91,
                'unit_id' => null,
                'value' => 2,
            ],
            [
                'recipe_id' => 25,
                'ingredient_id' => 114,
                'unit_id' => 6,
                'value' => 0.25,
            ],
            [
                'recipe_id' => 25,
                'ingredient_id' => 157,
                'unit_id' => 1,
                'value' => 120,
            ],
            [
                'recipe_id' => 25,
                'ingredient_id' => 40,
                'unit_id' => 6,
                'value' => 0.33,
            ],
            [
                'recipe_id' => 25,
                'ingredient_id' => 32,
                'unit_id' => 1,
                'value' => 850,
            ],
            [
                'recipe_id' => 26,
                'ingredient_id' => 35,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 26,
                'ingredient_id' => 140,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 26,
                'ingredient_id' => 25,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 26,
                'ingredient_id' => 81,
                'unit_id' => 1,
                'value' => 400,
            ],
            [
                'recipe_id' => 26,
                'ingredient_id' => 131,
                'unit_id' => null,
                'value' => 2,
            ],
            [
                'recipe_id' => 26,
                'ingredient_id' => 160,
                'unit_id' => 1,
                'value' => 1000,
            ],
            [
                'recipe_id' => 26,
                'ingredient_id' => 129,
                'unit_id' => 3,
                'value' => 100,
            ],
            [
                'recipe_id' => 26,
                'ingredient_id' => 115,
                'unit_id' => null,
                'value' => 5,
            ],
            [
                'recipe_id' => 26,
                'ingredient_id' => 70,
                'unit_id' => null,
                'value' => 3,
            ],
            [
                'recipe_id' => 26,
                'ingredient_id' => 95,
                'unit_id' => 1,
                'value' => 500,
            ],
            [
                'recipe_id' => 26,
                'ingredient_id' => 30,
                'unit_id' => 1,
                'value' => 50,
            ],
            [
                'recipe_id' => 26,
                'ingredient_id' => 54,
                'unit_id' => 1,
                'value' => 2000,
            ],
            [
                'recipe_id' => 27,
                'ingredient_id' => 35,
                'unit_id' => 7,
                'value' => 1,
            ],
            [
                'recipe_id' => 27,
                'ingredient_id' => 139,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 27,
                'ingredient_id' => 30,
                'unit_id' => 5,
                'value' => 1,
            ],
            [
                'recipe_id' => 27,
                'ingredient_id' => 62,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 27,
                'ingredient_id' => 38,
                'unit_id' => 1,
                'value' => 450,
            ],
            [
                'recipe_id' => 27,
                'ingredient_id' => 87,
                'unit_id' => 4,
                'value' => 1.5,
            ],
            [
                'recipe_id' => 27,
                'ingredient_id' => 67,
                'unit_id' => 6,
                'value' => 2.25,
            ],
            [
                'recipe_id' => 27,
                'ingredient_id' => 114,
                'unit_id' => 4,
                'value' => 2,
            ],
            [
                'recipe_id' => 27,
                'ingredient_id' => 6,
                'unit_id' => 14,
                'value' => 1,
            ],
            [
                'recipe_id' => 27,
                'ingredient_id' => 152,
                'unit_id' => 4,
                'value' => 1.5,
            ],
            [
                'recipe_id' => 27,
                'ingredient_id' => 173,
                'unit_id' => 6,
                'value' => 0.33,
            ],
            [
                'recipe_id' => 27,
                'ingredient_id' => 172,
                'unit_id' => 6,
                'value' => 0.5,
            ],
            [
                'recipe_id' => 28,
                'ingredient_id' => 12,
                'unit_id' => 1,
                'value' => 10,
            ],
            [
                'recipe_id' => 28,
                'ingredient_id' => 152,
                'unit_id' => 1,
                'value' => 200,
            ],
            [
                'recipe_id' => 28,
                'ingredient_id' => 30,
                'unit_id' => 1,
                'value' => 200,
            ],
            [
                'recipe_id' => 28,
                'ingredient_id' => 139,
                'unit_id' => 4,
                'value' => 1,
            ],
            [
                'recipe_id' => 28,
                'ingredient_id' => 173,
                'unit_id' => 2,
                'value' => 25,
            ],
            [
                'recipe_id' => 28,
                'ingredient_id' => 67,
                'unit_id' => 1,
                'value' => 350,
            ],
            [
                'recipe_id' => 29,
                'ingredient_id' => 140,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 29,
                'ingredient_id' => 114,
                'unit_id' => 5,
                'value' => 1,
            ],
            [
                'recipe_id' => 29,
                'ingredient_id' => 160,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 29,
                'ingredient_id' => 144,
                'unit_id' => 5,
                'value' => 1,
            ],
            [
                'recipe_id' => 29,
                'ingredient_id' => 60,
                'unit_id' => 5,
                'value' => 1,
            ],
            [
                'recipe_id' => 29,
                'ingredient_id' => 121,
                'unit_id' => 5,
                'value' => 3,
            ],
            [
                'recipe_id' => 29,
                'ingredient_id' => 70,
                'unit_id' => null,
                'value' => 4,
            ],
            [
                'recipe_id' => 29,
                'ingredient_id' => 132,
                'unit_id' => null,
                'value' => 3,
            ],
            [
                'recipe_id' => 29,
                'ingredient_id' => 64,
                'unit_id' => null,
                'value' => 3,
            ],
            [
                'recipe_id' => 30,
                'ingredient_id' => 139,
                'unit_id' => 5,
                'value' => 1,
            ],
            [
                'recipe_id' => 30,
                'ingredient_id' => 152,
                'unit_id' => 4,
                'value' => 1,
            ],
            [
                'recipe_id' => 30,
                'ingredient_id' => 168,
                'unit_id' => 3,
                'value' => 80,
            ],
            [
                'recipe_id' => 30,
                'ingredient_id' => 160,
                'unit_id' => 1,
                'value' => 907,
            ],
            [
                'recipe_id' => 30,
                'ingredient_id' => 132,
                'unit_id' => 1,
                'value' => 1810,
            ],
            [
                'recipe_id' => 31,
                'ingredient_id' => 140,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 31,
                'ingredient_id' => 60,
                'unit_id' => 1,
                'value' => 10,
            ],
            [
                'recipe_id' => 31,
                'ingredient_id' => 82,
                'unit_id' => 3,
                'value' => 250,
            ],
            [
                'recipe_id' => 31,
                'ingredient_id' => 138,
                'unit_id' => 1,
                'value' => 450,
            ],
            [
                'recipe_id' => 31,
                'ingredient_id' => 34,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 31,
                'ingredient_id' => 128,
                'unit_id' => 1,
                'value' => 450,
            ],
            [
                'recipe_id' => 31,
                'ingredient_id' => 66,
                'unit_id' => 2,
                'value' => 125,
            ],
            [
                'recipe_id' => 31,
                'ingredient_id' => 90,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 31,
                'ingredient_id' => 30,
                'unit_id' => 1,
                'value' => 50,
            ],
            [
                'recipe_id' => 32,
                'ingredient_id' => 120,
                'unit_id' => 5,
                'value' => 0.13,
            ],
            [
                'recipe_id' => 32,
                'ingredient_id' => 146,
                'unit_id' => 6,
                'value' => 0.25,
            ],
            [
                'recipe_id' => 32,
                'ingredient_id' => 119,
                'unit_id' => 6,
                'value' => 0.75,
            ],
            [
                'recipe_id' => 32,
                'ingredient_id' => 140,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 32,
                'ingredient_id' => 38,
                'unit_id' => 6,
                'value' => 3,
            ],
            [
                'recipe_id' => 32,
                'ingredient_id' => 83,
                'unit_id' => 6,
                'value' => 0.5,
            ],
            [
                'recipe_id' => 32,
                'ingredient_id' => 102,
                'unit_id' => 6,
                'value' => 1.5,
            ],
            [
                'recipe_id' => 32,
                'ingredient_id' => 67,
                'unit_id' => 6,
                'value' => 0.17,
            ],
            [
                'recipe_id' => 32,
                'ingredient_id' => 30,
                'unit_id' => 5,
                'value' => 5,
            ],
            [
                'recipe_id' => 32,
                'ingredient_id' => 114,
                'unit_id' => 5,
                'value' => 0.5,
            ],
            [
                'recipe_id' => 32,
                'ingredient_id' => 65,
                'unit_id' => 1,
                'value' => 250,
            ],
            [
                'recipe_id' => 33,
                'ingredient_id' => 139,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 33,
                'ingredient_id' => 35,
                'unit_id' => 7,
                'value' => 1,
            ],
            [
                'recipe_id' => 33,
                'ingredient_id' => 118,
                'unit_id' => 4,
                'value' => 1,
            ],
            [
                'recipe_id' => 33,
                'ingredient_id' => 114,
                'unit_id' => 5,
                'value' => 2,
            ],
            [
                'recipe_id' => 33,
                'ingredient_id' => 70,
                'unit_id' => null,
                'value' => 2,
            ],
            [
                'recipe_id' => 33,
                'ingredient_id' => 115,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 33,
                'ingredient_id' => 160,
                'unit_id' => 1,
                'value' => 800,
            ],
            [
                'recipe_id' => 34,
                'ingredient_id' => 92,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 34,
                'ingredient_id' => 113,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 34,
                'ingredient_id' => 61,
                'unit_id' => 5,
                'value' => 1,
            ],
            [
                'recipe_id' => 34,
                'ingredient_id' => 72,
                'unit_id' => 3,
                'value' => 60,
            ],
            [
                'recipe_id' => 35,
                'ingredient_id' => 121,
                'unit_id' => 5,
                'value' => 1,
            ],
            [
                'recipe_id' => 35,
                'ingredient_id' => 140,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 35,
                'ingredient_id' => 146,
                'unit_id' => 6,
                'value' => 0.25,
            ],
            [
                'recipe_id' => 35,
                'ingredient_id' => 148,
                'unit_id' => 6,
                'value' => 0.25,
            ],
            [
                'recipe_id' => 35,
                'ingredient_id' => 70,
                'unit_id' => null,
                'value' => 6,
            ],
            [
                'recipe_id' => 35,
                'ingredient_id' => 30,
                'unit_id' => 6,
                'value' => 0.33,
            ],
            [
                'recipe_id' => 35,
                'ingredient_id' => 85,
                'unit_id' => 6,
                'value' => 0.5,
            ],
            [
                'recipe_id' => 35,
                'ingredient_id' => 139,
                'unit_id' => 4,
                'value' => 1,
            ],
            [
                'recipe_id' => 35,
                'ingredient_id' => 128,
                'unit_id' => 1,
                'value' => 1000,
            ],
            [
                'recipe_id' => 36,
                'ingredient_id' => 45,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 36,
                'ingredient_id' => 174,
                'unit_id' => 3,
                'value' => 60,
            ],
            [
                'recipe_id' => 36,
                'ingredient_id' => 106,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 36,
                'ingredient_id' => 29,
                'unit_id' => 4,
                'value' => 1,
            ],
            [
                'recipe_id' => 36,
                'ingredient_id' => 93,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 37,
                'ingredient_id' => 93,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 37,
                'ingredient_id' => 106,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 37,
                'ingredient_id' => 74,
                'unit_id' => 10,
                'value' => null,
            ],
            [
                'recipe_id' => 37,
                'ingredient_id' => 73,
                'unit_id' => 3,
                'value' => 200,
            ],
            [
                'recipe_id' => 37,
                'ingredient_id' => 55,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 37,
                'ingredient_id' => 170,
                'unit_id' => 3,
                'value' => 50,
            ],
            [
                'recipe_id' => 38,
                'ingredient_id' => 140,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 38,
                'ingredient_id' => 146,
                'unit_id' => 1,
                'value' => 150,
            ],
            [
                'recipe_id' => 38,
                'ingredient_id' => 121,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 38,
                'ingredient_id' => 70,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 38,
                'ingredient_id' => 115,
                'unit_id' => null,
                'value' => 0.5,
            ],
            [
                'recipe_id' => 38,
                'ingredient_id' => 100,
                'unit_id' => 4,
                'value' => 3,
            ],
            [
                'recipe_id' => 38,
                'ingredient_id' => 148,
                'unit_id' => 2,
                'value' => 50,
            ],
            [
                'recipe_id' => 38,
                'ingredient_id' => 108,
                'unit_id' => 1,
                'value' => 300,
            ],
            [
                'recipe_id' => 38,
                'ingredient_id' => 136,
                'unit_id' => 1,
                'value' => 200,
            ],
            [
                'recipe_id' => 39,
                'ingredient_id' => 98,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 39,
                'ingredient_id' => 45,
                'unit_id' => 9,
                'value' => null,
            ],
            [
                'recipe_id' => 39,
                'ingredient_id' => 117,
                'unit_id' => 11,
                'value' => 1,
            ],
            [
                'recipe_id' => 39,
                'ingredient_id' => 26,
                'unit_id' => 3,
                'value' => 60,
            ],
            [
                'recipe_id' => 39,
                'ingredient_id' => 2,
                'unit_id' => 10,
                'value' => 3,
            ],
            [
                'recipe_id' => 39,
                'ingredient_id' => 152,
                'unit_id' => 12,
                'value' => 1,
            ],
            [
                'recipe_id' => 40,
                'ingredient_id' => 53,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 40,
                'ingredient_id' => 1,
                'unit_id' => null,
                'value' => 4,
            ],
            [
                'recipe_id' => 40,
                'ingredient_id' => 87,
                'unit_id' => 5,
                'value' => 0.5,
            ],
            [
                'recipe_id' => 40,
                'ingredient_id' => 114,
                'unit_id' => 5,
                'value' => 1,
            ],
            [
                'recipe_id' => 41,
                'ingredient_id' => 139,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 41,
                'ingredient_id' => 84,
                'unit_id' => 5,
                'value' => 3,
            ],
            [
                'recipe_id' => 41,
                'ingredient_id' => 46,
                'unit_id' => 1,
                'value' => 150,
            ],
            [
                'recipe_id' => 41,
                'ingredient_id' => 77,
                'unit_id' => 1,
                'value' => 100,
            ],
            [
                'recipe_id' => 41,
                'ingredient_id' => 86,
                'unit_id' => 1,
                'value' => 60,
            ],
            [
                'recipe_id' => 41,
                'ingredient_id' => 50,
                'unit_id' => 3,
                'value' => 20,
            ],
            [
                'recipe_id' => 41,
                'ingredient_id' => 165,
                'unit_id' => 3,
                'value' => 200,
            ],
            [
                'recipe_id' => 41,
                'ingredient_id' => 76,
                'unit_id' => 1,
                'value' => 200,
            ],
            [
                'recipe_id' => 42,
                'ingredient_id' => 150,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 42,
                'ingredient_id' => 51,
                'unit_id' => 6,
                'value' => 1,
            ],
            [
                'recipe_id' => 42,
                'ingredient_id' => 123,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 42,
                'ingredient_id' => 142,
                'unit_id' => 4,
                'value' => 1,
            ],
            [
                'recipe_id' => 42,
                'ingredient_id' => 78,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 42,
                'ingredient_id' => 10,
                'unit_id' => null,
                'value' => 0.5,
            ],
            [
                'recipe_id' => 42,
                'ingredient_id' => 131,
                'unit_id' => null,
                'value' => 0.5,
            ],
            [
                'recipe_id' => 42,
                'ingredient_id' => 97,
                'unit_id' => 6,
                'value' => 0.25,
            ],
            [
                'recipe_id' => 42,
                'ingredient_id' => 56,
                'unit_id' => 6,
                'value' => 0.25,
            ],
            [
                'recipe_id' => 42,
                'ingredient_id' => 31,
                'unit_id' => 6,
                'value' => 0.25,
            ],
            [
                'recipe_id' => 42,
                'ingredient_id' => 107,
                'unit_id' => 6,
                'value' => 2,
            ],
            [
                'recipe_id' => 42,
                'ingredient_id' => 154,
                'unit_id' => 1,
                'value' => 200,
            ],
            [
                'recipe_id' => 43,
                'ingredient_id' => 110,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 43,
                'ingredient_id' => 53,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 43,
                'ingredient_id' => 51,
                'unit_id' => 1,
                'value' => 200,
            ],
            [
                'recipe_id' => 43,
                'ingredient_id' => 144,
                'unit_id' => 5,
                'value' => 1,
            ],
            [
                'recipe_id' => 43,
                'ingredient_id' => 152,
                'unit_id' => 1,
                'value' => 50,
            ],
            [
                'recipe_id' => 43,
                'ingredient_id' => 50,
                'unit_id' => 3,
                'value' => 500,
            ],
            [
                'recipe_id' => 43,
                'ingredient_id' => 70,
                'unit_id' => null,
                'value' => 2,
            ],
            [
                'recipe_id' => 43,
                'ingredient_id' => 150,
                'unit_id' => 5,
                'value' => 2,
            ],
            [
                'recipe_id' => 43,
                'ingredient_id' => 127,
                'unit_id' => 1,
                'value' => 800,
            ],
            [
                'recipe_id' => 44,
                'ingredient_id' => 149,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 44,
                'ingredient_id' => 9,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 44,
                'ingredient_id' => 168,
                'unit_id' => 6,
                'value' => 0.25,
            ],
            [
                'recipe_id' => 44,
                'ingredient_id' => 53,
                'unit_id' => 4,
                'value' => 0.5,
            ],
            [
                'recipe_id' => 44,
                'ingredient_id' => 71,
                'unit_id' => 4,
                'value' => 1,
            ],
            [
                'recipe_id' => 44,
                'ingredient_id' => 87,
                'unit_id' => 4,
                'value' => 1,
            ],
            [
                'recipe_id' => 44,
                'ingredient_id' => 67,
                'unit_id' => 5,
                'value' => 2,
            ],
            [
                'recipe_id' => 44,
                'ingredient_id' => 62,
                'unit_id' => null,
                'value' => 2,
            ],
            [
                'recipe_id' => 44,
                'ingredient_id' => 155,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 44,
                'ingredient_id' => 128,
                'unit_id' => null,
                'value' => 4,
            ],
            [
                'recipe_id' => 45,
                'ingredient_id' => 174,
                'unit_id' => 2,
                'value' => 5,
            ],
            [
                'recipe_id' => 45,
                'ingredient_id' => 102,
                'unit_id' => 2,
                'value' => 100,
            ],
            [
                'recipe_id' => 45,
                'ingredient_id' => 30,
                'unit_id' => 1,
                'value' => 90,
            ],
            [
                'recipe_id' => 45,
                'ingredient_id' => 62,
                'unit_id' => null,
                'value' => 6,
            ],
            [
                'recipe_id' => 45,
                'ingredient_id' => 152,
                'unit_id' => 1,
                'value' => 75,
            ],
            [
                'recipe_id' => 45,
                'ingredient_id' => 139,
                'unit_id' => 7,
                'value' => 3,
            ],
            [
                'recipe_id' => 45,
                'ingredient_id' => 67,
                'unit_id' => 1,
                'value' => 375,
            ],
            [
                'recipe_id' => 46,
                'ingredient_id' => 140,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 46,
                'ingredient_id' => 111,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 46,
                'ingredient_id' => 102,
                'unit_id' => 2,
                'value' => 20,
            ],
            [
                'recipe_id' => 46,
                'ingredient_id' => 148,
                'unit_id' => 2,
                'value' => 20,
            ],
            [
                'recipe_id' => 46,
                'ingredient_id' => 62,
                'unit_id' => null,
                'value' => 3,
            ],
            [
                'recipe_id' => 46,
                'ingredient_id' => 30,
                'unit_id' => 1,
                'value' => 30,
            ],
            [
                'recipe_id' => 46,
                'ingredient_id' => 11,
                'unit_id' => 1,
                'value' => 200,
            ],
            [
                'recipe_id' => 46,
                'ingredient_id' => 145,
                'unit_id' => 1,
                'value' => 200,
            ],
            [
                'recipe_id' => 47,
                'ingredient_id' => 140,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 47,
                'ingredient_id' => 19,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 47,
                'ingredient_id' => 159,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 47,
                'ingredient_id' => 114,
                'unit_id' => 5,
                'value' => 6,
            ],
            [
                'recipe_id' => 47,
                'ingredient_id' => 70,
                'unit_id' => null,
                'value' => 3,
            ],
            [
                'recipe_id' => 47,
                'ingredient_id' => 160,
                'unit_id' => 1,
                'value' => 500,
            ],
            [
                'recipe_id' => 47,
                'ingredient_id' => 115,
                'unit_id' => 1,
                'value' => 350,
            ],
            [
                'recipe_id' => 47,
                'ingredient_id' => 131,
                'unit_id' => 1,
                'value' => 350,
            ],
            [
                'recipe_id' => 47,
                'ingredient_id' => 178,
                'unit_id' => 1,
                'value' => 350,
            ],
            [
                'recipe_id' => 47,
                'ingredient_id' => 64,
                'unit_id' => 1,
                'value' => 350,
            ],
            [
                'recipe_id' => 48,
                'ingredient_id' => 151,
                'unit_id' => 8,
                'value' => 4,
            ],
            [
                'recipe_id' => 48,
                'ingredient_id' => 62,
                'unit_id' => 1,
                'value' => 1,
            ],
            [
                'recipe_id' => 48,
                'ingredient_id' => 114,
                'unit_id' => 6,
                'value' => 0.25,
            ],
            [
                'recipe_id' => 48,
                'ingredient_id' => 139,
                'unit_id' => 4,
                'value' => 0.5,
            ],
            [
                'recipe_id' => 48,
                'ingredient_id' => 144,
                'unit_id' => 4,
                'value' => 2,
            ],
            [
                'recipe_id' => 48,
                'ingredient_id' => 28,
                'unit_id' => 6,
                'value' => 2,
            ],
            [
                'recipe_id' => 48,
                'ingredient_id' => 70,
                'unit_id' => null,
                'value' => 2,
            ],
            [
                'recipe_id' => 48,
                'ingredient_id' => 160,
                'unit_id' => null,
                'value' => 9,
            ],
            [
                'recipe_id' => 49,
                'ingredient_id' => 140,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 49,
                'ingredient_id' => 38,
                'unit_id' => 1,
                'value' => 100,
            ],
            [
                'recipe_id' => 49,
                'ingredient_id' => 28,
                'unit_id' => 8,
                'value' => 6,
            ],
            [
                'recipe_id' => 50,
                'ingredient_id' => 41,
                'unit_id' => null,
                'value' => 3,
            ],
            [
                'recipe_id' => 50,
                'ingredient_id' => 114,
                'unit_id' => 1,
                'value' => 70,
            ],
            [
                'recipe_id' => 50,
                'ingredient_id' => 139,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 50,
                'ingredient_id' => 70,
                'unit_id' => null,
                'value' => 3,
            ],
            [
                'recipe_id' => 50,
                'ingredient_id' => 5,
                'unit_id' => 1,
                'value' => 320,
            ],
            [
                'recipe_id' => 51,
                'ingredient_id' => 33,
                'unit_id' => 1,
                'value' => 475,
            ],
            [
                'recipe_id' => 51,
                'ingredient_id' => 142,
                'unit_id' => 4,
                'value' => 1,
            ],
            [
                'recipe_id' => 51,
                'ingredient_id' => 51,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 51,
                'ingredient_id' => 29,
                'unit_id' => 5,
                'value' => 6,
            ],
            [
                'recipe_id' => 51,
                'ingredient_id' => 96,
                'unit_id' => 5,
                'value' => 2,
            ],
            [
                'recipe_id' => 51,
                'ingredient_id' => 161,
                'unit_id' => 3,
                'value' => 150,
            ],
            [
                'recipe_id' => 51,
                'ingredient_id' => 105,
                'unit_id' => 4,
                'value' => 1,
            ],
            [
                'recipe_id' => 51,
                'ingredient_id' => 70,
                'unit_id' => null,
                'value' => 2,
            ],
            [
                'recipe_id' => 51,
                'ingredient_id' => 131,
                'unit_id' => null,
                'value' => 2,
            ],
            [
                'recipe_id' => 51,
                'ingredient_id' => 115,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 51,
                'ingredient_id' => 39,
                'unit_id' => null,
                'value' => 3,
            ],
            [
                'recipe_id' => 51,
                'ingredient_id' => 120,
                'unit_id' => 4,
                'value' => 2,
            ],
            [
                'recipe_id' => 51,
                'ingredient_id' => 71,
                'unit_id' => 4,
                'value' => 0.5,
            ],
            [
                'recipe_id' => 51,
                'ingredient_id' => 140,
                'unit_id' => 4,
                'value' => 0.5,
            ],
            [
                'recipe_id' => 51,
                'ingredient_id' => 67,
                'unit_id' => 1,
                'value' => 90,
            ],
            [
                'recipe_id' => 51,
                'ingredient_id' => 52,
                'unit_id' => 5,
                'value' => 3,
            ],
            [
                'recipe_id' => 51,
                'ingredient_id' => 62,
                'unit_id' => null,
                'value' => 5,
            ],
            [
                'recipe_id' => 51,
                'ingredient_id' => 168,
                'unit_id' => 5,
                'value' => 6,
            ],
            [
                'recipe_id' => 52,
                'ingredient_id' => 139,
                'unit_id' => 4,
                'value' => 0.75,
            ],
            [
                'recipe_id' => 52,
                'ingredient_id' => 63,
                'unit_id' => null,
                'value' => 3,
            ],
            [
                'recipe_id' => 52,
                'ingredient_id' => 168,
                'unit_id' => 3,
                'value' => 125,
            ],
            [
                'recipe_id' => 52,
                'ingredient_id' => 125,
                'unit_id' => 1,
                'value' => 250,
            ],
            [
                'recipe_id' => 52,
                'ingredient_id' => 173,
                'unit_id' => 5,
                'value' => 2,
            ],
            [
                'recipe_id' => 52,
                'ingredient_id' => 137,
                'unit_id' => 4,
                'value' => 1,
            ],
            [
                'recipe_id' => 52,
                'ingredient_id' => 30,
                'unit_id' => 5,
                'value' => 2,
            ],
            [
                'recipe_id' => 52,
                'ingredient_id' => 16,
                'unit_id' => 6,
                'value' => 0.5,
            ],
            [
                'recipe_id' => 52,
                'ingredient_id' => 50,
                'unit_id' => 3,
                'value' => 3000,
            ],
            [
                'recipe_id' => 52,
                'ingredient_id' => 139,
                'unit_id' => 5,
                'value' => 1,
            ],
            [
                'recipe_id' => 52,
                'ingredient_id' => 18,
                'unit_id' => 1,
                'value' => 360,
            ],
            [
                'recipe_id' => 53,
                'ingredient_id' => 114,
                'unit_id' => 5,
                'value' => 3,
            ],
            [
                'recipe_id' => 53,
                'ingredient_id' => 142,
                'unit_id' => 1,
                'value' => 600,
            ],
            [
                'recipe_id' => 54,
                'ingredient_id' => 109,
                'unit_id' => 5,
                'value' => 1,
            ],
            [
                'recipe_id' => 54,
                'ingredient_id' => 140,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 54,
                'ingredient_id' => 121,
                'unit_id' => 5,
                'value' => 1,
            ],
            [
                'recipe_id' => 54,
                'ingredient_id' => 62,
                'unit_id' => null,
                'value' => 6,
            ],
            [
                'recipe_id' => 54,
                'ingredient_id' => 102,
                'unit_id' => 3,
                'value' => 250,
            ],
            [
                'recipe_id' => 54,
                'ingredient_id' => 67,
                'unit_id' => 1,
                'value' => 20,
            ],
            [
                'recipe_id' => 54,
                'ingredient_id' => 30,
                'unit_id' => 1,
                'value' => 20,
            ],
            [
                'recipe_id' => 54,
                'ingredient_id' => 148,
                'unit_id' => 3,
                'value' => 250,
            ],
            [
                'recipe_id' => 54,
                'ingredient_id' => 171,
                'unit_id' => 1,
                'value' => 100,
            ],
            [
                'recipe_id' => 54,
                'ingredient_id' => 135,
                'unit_id' => 1,
                'value' => 300,
            ],
            [
                'recipe_id' => 54,
                'ingredient_id' => 145,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 55,
                'ingredient_id' => 4,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 55,
                'ingredient_id' => 70,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 55,
                'ingredient_id' => 114,
                'unit_id' => 5,
                'value' => 2,
            ],
            [
                'recipe_id' => 55,
                'ingredient_id' => 115,
                'unit_id' => 1,
                'value' => 200,
            ],
            [
                'recipe_id' => 55,
                'ingredient_id' => 11,
                'unit_id' => 1,
                'value' => 200,
            ],
            [
                'recipe_id' => 55,
                'ingredient_id' => 128,
                'unit_id' => 1,
                'value' => 1000,
            ],
            [
                'recipe_id' => 56,
                'ingredient_id' => 49,
                'unit_id' => 5,
                'value' => 1,
            ],
            [
                'recipe_id' => 56,
                'ingredient_id' => 22,
                'unit_id' => 5,
                'value' => 1,
            ],
            [
                'recipe_id' => 56,
                'ingredient_id' => 23,
                'unit_id' => 6,
                'value' => 1,
            ],
            [
                'recipe_id' => 56,
                'ingredient_id' => 88,
                'unit_id' => 1,
                'value' => 300,
            ],
            [
                'recipe_id' => 56,
                'ingredient_id' => 100,
                'unit_id' => 1,
                'value' => 500,
            ],
            [
                'recipe_id' => 56,
                'ingredient_id' => 102,
                'unit_id' => 6,
                'value' => 0.5,
            ],
            [
                'recipe_id' => 56,
                'ingredient_id' => 152,
                'unit_id' => 1,
                'value' => 100,
            ],
            [
                'recipe_id' => 56,
                'ingredient_id' => 62,
                'unit_id' => null,
                'value' => 4,
            ],
            [
                'recipe_id' => 57,
                'ingredient_id' => 140,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 57,
                'ingredient_id' => 121,
                'unit_id' => 5,
                'value' => 1,
            ],
            [
                'recipe_id' => 57,
                'ingredient_id' => 148,
                'unit_id' => 5,
                'value' => 2,
            ],
            [
                'recipe_id' => 57,
                'ingredient_id' => 91,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 57,
                'ingredient_id' => 102,
                'unit_id' => 3,
                'value' => 500,
            ],
            [
                'recipe_id' => 57,
                'ingredient_id' => 24,
                'unit_id' => 3,
                'value' => 250,
            ],
            [
                'recipe_id' => 57,
                'ingredient_id' => 67,
                'unit_id' => 5,
                'value' => 2,
            ],
            [
                'recipe_id' => 57,
                'ingredient_id' => 108,
                'unit_id' => 1,
                'value' => 250,
            ],
            [
                'recipe_id' => 57,
                'ingredient_id' => 115,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 57,
                'ingredient_id' => 30,
                'unit_id' => 5,
                'value' => 3,
            ],
            [
                'recipe_id' => 58,
                'ingredient_id' => 146,
                'unit_id' => 1,
                'value' => 60,
            ],
            [
                'recipe_id' => 58,
                'ingredient_id' => 30,
                'unit_id' => 1,
                'value' => 20,
            ],
            [
                'recipe_id' => 58,
                'ingredient_id' => 169,
                'unit_id' => 2,
                'value' => 80,
            ],
            [
                'recipe_id' => 58,
                'ingredient_id' => 140,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 58,
                'ingredient_id' => 148,
                'unit_id' => 2,
                'value' => 15,
            ],
            [
                'recipe_id' => 58,
                'ingredient_id' => 115,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 58,
                'ingredient_id' => 133,
                'unit_id' => null,
                'value' => 1,
            ],
            [
                'recipe_id' => 59,
                'ingredient_id' => 112,
                'unit_id' => 5,
                'value' => 3,
            ],
            [
                'recipe_id' => 59,
                'ingredient_id' => 112,
                'unit_id' => 6,
                'value' => 0.33,
            ],
            [
                'recipe_id' => 59,
                'ingredient_id' => 173,
                'unit_id' => 6,
                'value' => 1,
            ],
            [
                'recipe_id' => 59,
                'ingredient_id' => 139,
                'unit_id' => 4,
                'value' => 0.5,
            ],
            [
                'recipe_id' => 59,
                'ingredient_id' => 13,
                'unit_id' => 4,
                'value' => 0.5,
            ],
            [
                'recipe_id' => 59,
                'ingredient_id' => 67,
                'unit_id' => 6,
                'value' => 1,
            ],
            [
                'recipe_id' => 59,
                'ingredient_id' => 176,
                'unit_id' => 6,
                'value' => 1.5,
            ],
            [
                'recipe_id' => 60,
                'ingredient_id' => 30,
                'unit_id' => 1,
                'value' => 100,
            ],
            [
                'recipe_id' => 60,
                'ingredient_id' => 67,
                'unit_id' => 1,
                'value' => 100,
            ],
            [
                'recipe_id' => 60,
                'ingredient_id' => 140,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 60,
                'ingredient_id' => 143,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 60,
                'ingredient_id' => 114,
                'unit_id' => null,
                'value' => null,
            ],
            [
                'recipe_id' => 60,
                'ingredient_id' => 17,
                'unit_id' => 13,
                'value' => 2,
            ],
            [
                'recipe_id' => 60,
                'ingredient_id' => 146,
                'unit_id' => 1,
                'value' => 100,
            ],
            [
                'recipe_id' => 60,
                'ingredient_id' => 178,
                'unit_id' => 1,
                'value' => 1000,
            ],
        ];

        foreach ($recipeingredientunits as $recipeingredientunit) {
            RecipeIngredientUnit::create($recipeingredientunit);
        }

        Schema::enableForeignKeyConstraints();
    }
}

// 'id' => 152,
// 'name' => 'sugar',

// 'id' => 67,
// 'name' => 'flour',

// 'id' => 102,
// 'name' => 'milk',

// 'id' => 62,
// 'name' => 'egg',

// 'id' => 63,
// 'name' => 'egg yolk',

// 'id' => 30,
//  'name' => 'butter',

//  'id' => 114,
//  'name' => 'olive oil',

//  'id' => 87,
// 'name' => 'kosher salt',

// 'id' => 139,
// 'name' => 'salt',

// 'id' => 140,
// 'name' => 'salt and pepper',

// 'id' => 53,
// 'name' => 'cracked black pepper',

// 'id' => 34,
// 'name' => 'carrot',

// 'id' => 143,
// 'name' => 'shallot',

// 'id' => 115,
//  'name' => 'onion',

//  'id' => 70,
//  'name' => 'garlic clove',

//  'id' => 71,
//  'name' => 'garlic powder',

//  'id' => 104,
//  'name' => 'minced garlic',


//  'id' => 93,
//  'name' => 'lime',

//  'id' => 160,
//  'name' => 'tomato',
// ],
