<?php

namespace Database\Seeders;

use App\Models\Recipe;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class RecipesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        Recipe::truncate();

        $recipes = [
            [
                'id' => 1,
                'category_id' => 4, // Dessert
                'name' => 'Banana Bread',
                'prep_time' => 10,
                'cook_time' => 55,
                'rest_time' => 0,
                'servings' => 10,
            ],
            [
                'id' => 2,
                'category_id' => 2, // Main Dish
                'name' => 'Boeuf Bourguignon',
                'prep_time' => 6,
                'cook_time' => 300,
                'rest_time' => 0,
                'servings' => 4,
            ],
            [
                'id' => 3,
                'category_id' => 6, // Other
                'name' => 'Bolognese Sauce',
                'prep_time' => 20,
                'cook_time' => 180,
                'rest_time' => 0,
                'servings' => 6,
            ],
            [
                'id' => 4,
                'category_id' => 2,
                'name' => 'Brisket',
                'prep_time' => 10,
                'cook_time' => 240,
                'rest_time' => 10,
                'servings' => 4,
            ],
            [
                'id' => 5,
                'category_id' => 1, // Appetizer
                'name' => 'Cake Jambon Olives',
                'prep_time' => 20,
                'cook_time' => 45,
                'rest_time' => 0,
                'servings' => 6,
            ],
            [
                'id' => 6,
                'category_id' => 4,
                'name' => 'Cannelés',
                'prep_time' => 15,
                'cook_time' => 75,
                'rest_time' => 0,
                'servings' => 12,
            ],
            [
                'id' => 7,
                'category_id' => 2,
                'name' => 'Carbonade flamande',
                'prep_time' => 30,
                'cook_time' => 190,
                'rest_time' => 0,
                'servings' => 4,
            ],
            [
                'id' => 8,
                'category_id' => 6,
                'name' => 'Carbonara Sauce',
                'prep_time' => 10,
                'cook_time' => 10,
                'rest_time' => 0,
                'servings' => 4,
            ],
            [
                'id' => 9,
                'category_id' => 4,
                'name' => 'Cherry Vareniki',
                'prep_time' => 105,
                'cook_time' => 5,
                'rest_time' => 0,
                'servings' => 45,
            ],
            [
                'id' => 10,
                'category_id' => 2,
                'name' => 'Chicken & Mushrooms Julienne',
                'prep_time' => 10,
                'cook_time' => 35,
                'rest_time' => 0,
                'servings' => 4,
            ],
            [
                'id' => 11,
                'category_id' => 2,
                'name' => 'Chicken Fried Rice',
                'prep_time' => 5,
                'cook_time' => 10,
                'rest_time' => 0,
                'servings' => 6,
            ],
            [
                'id' => 12,
                'category_id' => 2,
                'name' => 'Coconut Chicken Curry',
                'prep_time' => 15,
                'cook_time' => 35,
                'rest_time' => 0,
                'servings' => 5,
            ],
            [
                'id' => 13,
                'category_id' => 4,
                'name' => 'Crème brûlée à la vanille',
                'prep_time' => 20,
                'cook_time' => 35,
                'rest_time' => 0,
                'servings' => 8,
            ],
            [
                'id' => 14,
                'category_id' => 5, // Cocktails
                'name' => 'Daiquiri',
                'prep_time' => 5,
                'cook_time' => 0,
                'rest_time' => 0,
                'servings' => 1,
            ],
            [
                'id' => 15,
                'category_id' => 4,
                'name' => 'Far breton',
                'prep_time' => 15,
                'cook_time' => 35,
                'rest_time' => 0,
                'servings' => 8,
            ],
            [
                'id' => 16,
                'category_id' => 4,
                'name' => 'Fondant au chocolat',
                'prep_time' => 15,
                'cook_time' => 30,
                'rest_time' => 0,
                'servings' => 6,
            ],
            [
                'id' => 17,
                'category_id' => 3, // Side Dish
                'name' => 'Fresh Pasta',
                'prep_time' => 70,
                'cook_time' => 2,
                'rest_time' => 0,
                'servings' => 4,
            ],
            [
                'id' => 18,
                'category_id' => 2,
                'name' => 'Fricassée de porc',
                'prep_time' => 30,
                'cook_time' => 120,
                'rest_time' => 0,
                'servings' => 4,
            ],
            [
                'id' => 19,
                'category_id' => 5,
                'name' => 'Frozen Margarita',
                'prep_time' => 5,
                'cook_time' => 0,
                'rest_time' => 0,
                'servings' => 1,
            ],
            [
                'id' => 20,
                'category_id' => 4,
                'name' => 'Galette des Rois',
                'prep_time' => 15,
                'cook_time' => 40,
                'rest_time' => 0,
                'servings' => 6,
            ],
            [
                'id' => 21,
                'category_id' => 6,
                'name' => 'Genovese Pesto Sauce',
                'prep_time' => 10,
                'cook_time' => 0,
                'rest_time' => 0,
                'servings' => 6,
            ],
            [
                'id' => 22,
                'category_id' => 4,
                'name' => 'Gratin Dauphinois',
                'prep_time' => 10,
                'cook_time' => 55,
                'rest_time' => 0,
                'servings' => 10,
            ],
            [
                'id' => 23,
                'category_id' => 1,
                'name' => 'Guacamole',
                'prep_time' => 10,
                'cook_time' => 0,
                'rest_time' => 0,
                'servings' => 4,
            ],
            [
                'id' => 24,
                'category_id' => 4,
                'name' => 'Gâteau au Petit-Beurre',
                'prep_time' => 40,
                'cook_time' => 0,
                'rest_time' => 86400,
                'servings' => 8,
            ],
            [
                'id' => 25,
                'category_id' => 1,
                'name' => 'Hummus',
                'prep_time' => 3,
                'cook_time' => 3,
                'rest_time' => 0,
                'servings' => 8,
            ],
            [
                'id' => 26,
                'category_id' => 3,
                'name' => 'Jambalaya',
                'prep_time' => 30,
                'cook_time' => 35,
                'rest_time' => 0,
                'servings' => 6,
            ],
            [
                'id' => 27,
                'category_id' => 1,
                'name' => 'Khachapuri',
                'prep_time' => 30,
                'cook_time' => 20,
                'rest_time' => 0,
                'servings' => 4,
            ],
            [
                'id' => 28,
                'category_id' => 4,
                'name' => 'Kouign Amann',
                'prep_time' => 60,
                'cook_time' => 25,
                'rest_time' => 60,
                'servings' => 8,
            ],
            [
                'id' => 29,
                'category_id' => 1,
                'name' => 'Kyopolou',
                'prep_time' => 20,
                'cook_time' => 40,
                'rest_time' => 10,
                'servings' => 3,
            ],
            [
                'id' => 30,
                'category_id' => 1,
                'name' => 'Ljutenitsa',
                'prep_time' => 60,
                'cook_time' => 90,
                'rest_time' => 0,
                'servings' => 20,
            ],
            [
                'id' => 31,
                'category_id' => 2,
                'name' => 'Lohikeitto',
                'prep_time' => 10,
                'cook_time' => 25,
                'rest_time' => 0,
                'servings' => 4,
            ],
            [
                'id' => 32,
                'category_id' => 3,
                'name' => 'Mac & Cheese',
                'prep_time' => 20,
                'cook_time' => 30,
                'rest_time' => 0,
                'servings' => 6,
            ],
            [
                'id' => 33,
                'category_id' => 6,
                'name' => 'Marinara Sauce',
                'prep_time' => 5,
                'cook_time' => 45,
                'rest_time' => 0,
                'servings' => 2,
            ],
            [
                'id' => 34,
                'category_id' => 5,
                'name' => 'Martini',
                'prep_time' => 5,
                'cook_time' => 0,
                'rest_time' => 0,
                'servings' => 1,
            ],
            [
                'id' => 35,
                'category_id' => 3,
                'name' => 'Mashed Potatoes',
                'prep_time' => 10,
                'cook_time' => 30,
                'rest_time' => 0,
                'servings' => 4,
            ],
            [
                'id' => 36,
                'category_id' => 5,
                'name' => 'Mojito',
                'prep_time' => 5,
                'cook_time' => 0,
                'rest_time' => 0,
                'servings' => 1,
            ],
            [
                'id' => 37,
                'category_id' => 5,
                'name' => 'Moscow Mule',
                'prep_time' => 5,
                'cook_time' => 0,
                'rest_time' => 0,
                'servings' => 1,
            ],
            [
                'id' => 38,
                'category_id' => 2,
                'name' => 'Mushroom Risotto',
                'prep_time' => 30,
                'cook_time' => 45,
                'rest_time' => 0,
                'servings' => 4,
            ],
            [
                'id' => 39,
                'category_id' => 5,
                'name' => 'Old Fashioned',
                'prep_time' => 5,
                'cook_time' => 0,
                'rest_time' => 0,
                'servings' => 1,
            ],
            [
                'id' => 40,
                'category_id' => 2,
                'name' => 'Pan Seared Salmon',
                'prep_time' => 5,
                'cook_time' => 10,
                'rest_time' => 0,
                'servings' => 4,
            ],
            [
                'id' => 41,
                'category_id' => 5,
                'name' => 'Perle de coco',
                'prep_time' => 180,
                'cook_time' => 60,
                'rest_time' => 0,
                'servings' => 12,
            ],
            [
                'id' => 42,
                'category_id' => 2,
                'name' => 'Poke Bowl',
                'prep_time' => 10,
                'cook_time' => 0,
                'rest_time' => 0,
                'servings' => 2,
            ],
            [
                'id' => 43,
                'category_id' => 2,
                'name' => 'Porc au caramel',
                'prep_time' => 30,
                'cook_time' => 120,
                'rest_time' => 0,
                'servings' => 4,
            ],
            [
                'id' => 44,
                'category_id' => 3,
                'name' => 'Potato Pancakes',
                'prep_time' => 30,
                'cook_time' => 30,
                'rest_time' => 0,
                'servings' => 6,
            ],
            [
                'id' => 45,
                'category_id' => 5,
                'name' => 'Pâte à Crêpes',
                'prep_time' => 15,
                'cook_time' => 2,
                'rest_time' => 0,
                'servings' => 6,
            ],
            [
                'id' => 46,
                'category_id' => 1,
                'name' => 'Quiche Lorraine',
                'prep_time' => 15,
                'cook_time' => 45,
                'rest_time' => 0,
                'servings' => 4,
            ],
            [
                'id' => 47,
                'category_id' => 3,
                'name' => 'Ratatouille',
                'prep_time' => 20,
                'cook_time' => 55,
                'rest_time' => 0,
                'servings' => 4,
            ],
            [
                'id' => 48,
                'category_id' => 1,
                'name' => 'Salmorejo',
                'prep_time' => 10,
                'cook_time' => 2,
                'rest_time' => 120,
                'servings' => 4,
            ],
            [
                'id' => 49,
                'category_id' => 1,
                'name' => 'Soupe à l\'oignon',
                'prep_time' => 25,
                'cook_time' => 20,
                'rest_time' => 0,
                'servings' => 4,
            ],
            [
                'id' => 50,
                'category_id' => 2,
                'name' => 'Spaghetti aglio olio e peperoncino',
                'prep_time' => 5,
                'cook_time' => 10,
                'rest_time' => 0,
                'servings' => 4,
            ],
            [
                'id' => 51,
                'category_id' => 2,
                'name' => 'Sweet and Sour Chicken',
                'prep_time' => 10,
                'cook_time' => 15,
                'rest_time' => 0,
                'servings' => 4,
            ],
            [
                'id' => 52,
                'category_id' => 3,
                'name' => 'Tachin (Persian Saffron Rice)',
                'prep_time' => 15,
                'cook_time' => 80,
                'rest_time' => 10,
                'servings' => 9,
            ],
            [
                'id' => 53,
                'category_id' => 1,
                'name' => 'Tahini',
                'prep_time' => 2,
                'cook_time' => 6,
                'rest_time' => 0,
                'servings' => 16,
            ],
            [
                'id' => 54,
                'category_id' => 1,
                'name' => 'Tarte Roquefort Noix',
                'prep_time' => 40,
                'cook_time' => 50,
                'rest_time' => 0,
                'servings' => 8,
            ],
            [
                'id' => 55,
                'category_id' => 2,
                'name' => 'Tartiflette',
                'prep_time' => 15,
                'cook_time' => 60,
                'rest_time' => 0,
                'servings' => 4,
            ],
            [
                'id' => 56,
                'category_id' => 4,
                'name' => 'Tiramisu',
                'prep_time' => 30,
                'cook_time' => 0,
                'rest_time' => 1440,
                'servings' => 6,
            ],
            [
                'id' => 57,
                'category_id' => 1,
                'name' => 'Velouté de champignons',
                'prep_time' => 10,
                'cook_time' => 40,
                'rest_time' => 0,
                'servings' => 3,
            ],
            [
                'id' => 58,
                'category_id' => 1,
                'name' => 'Veloutée de Potimarron',
                'prep_time' => 20,
                'cook_time' => 40,
                'rest_time' => 0,
                'servings' => 6,
            ],
            [
                'id' => 59,
                'category_id' => 6,
                'name' => 'Viking Bread',
                'prep_time' => 15,
                'cook_time' => 45,
                'rest_time' => 0,
                'servings' => 8,
            ],
            [
                'id' => 60,
                'category_id' => 3,
                'name' => 'Zucchini Crumble',
                'prep_time' => 20,
                'cook_time' => 25,
                'rest_time' => 0,
                'servings' => 6,
            ],
        ];

        foreach ($recipes as $recipe) {
            Recipe::create($recipe);
        }

        Schema::enableForeignKeyConstraints();
    }
}
